version: "3"

services:
  mynote-db:
    build: ./mynote-db
    image: mynote-db:stable
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynote
    volumes:
      - ./mynote-db/data:/var/lib/postgresql/data
  mynote-be:
    build: ./mynote-be
    image: mynote-be:stable
    depends_on:
      - mynote-db
    ports:
      - "10000"
    networks:
      - mynote
    environment:
      - DB_URL=mynote-db
      - DB_PORT=5432
      - APP_DB_USERNAME=postgres
      - APP_DB_PASSWORD=postgres
      - DB_NAME=postgres
  mynote-fe:
    build: ./mynote-fe
    image: mynote-fe:stable3
    depends_on:
      - mynote-be
    networks:
      - mynote
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mynote.entrypoints=http"
      - "traefik.http.routers.mynote.rule=Host(`mynote.svc.localgalaxy.org`)"
      - "traefik.http.middlewares.mynote-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mynote.middlewares=mynote-https-redirect"
      - "traefik.http.routers.mynote-secure.entrypoints=https"
      - "traefik.http.routers.mynote-secure.rule=Host(`mynote.svc.localgalaxy.org`)"
      - "traefik.http.routers.mynote-secure.tls=true"
      - "traefik.http.routers.mynote-secure.service=mynote"
      - "traefik.http.services.mynote.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
  mynote-lb:
    build: ./mynote-lb
    image: mynote-lb:stable
    depends_on:
      - mynote-be
    ports:
      - "4000:4000"
    networks:
      - mynote
networks:
  proxy:
    external: true
  mynote:
    external: false
