version: "3"

services:
  mynote-db:
    build: ./mynote-db
    image: mynote-db:stable
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./mynote-db/data:/var/lib/postgresql/data
  mynote-be:
    build: ./mynote-be
    image: mynote-be:stable
    depends_on:
      - mynote-db
    ports:
      - "10000"
    environment:
      - DB_URL=mynote-db
      - DB_PORT=5432
      - APP_DB_USERNAME=postgres
      - APP_DB_PASSWORD=postgres
      - DB_NAME=postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose","--tries=1","--spider", "http://localhost:10000/api/health-check"]
      interval: 1s
      timeout: 3s
      retries: 60
  mynote-fe:
    build: ./mynote-fe
    image: mynote-fe:stable3
    depends_on:
      - mynote-be
    ports:
      - "8082:80"
  mynote-lb:
    build: ./mynote-lb
    image: mynote-lb:stable 
    depends_on:
      - mynote-be
    ports:
      - "4000:4000"

