api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
