apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.be.name }} 
  name: {{ .Values.be.name }}
spec:
  ports:
  - port: {{ .Values.be.port }} 
    protocol: TCP
    targetPort: {{ .Values.be.port }} 
  selector:
    app: {{ .Values.be.name }} 
  type: ClusterIP 