apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }} 
  labels:
    app: {{ .Values.db.name }} 
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.db.name}} 
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - image: {{ .Values.db.image }}
          name: {{ .Values.db.name}}
          imagePullPolicy: {{ .Values.db.pullPolicy }}
          ports:
            - name: be
              containerPort: {{ .Values.db.port }} 
              protocol: TCP
          envFrom:
            - configMapRef:
                name: db-config