apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.db.name }} 
  name: {{ .Values.db.name }}
spec:
  ports:
  - port: {{ .Values.db.port }} 
    protocol: TCP
    targetPort: {{ .Values.db.port }} 
  selector:
    app: {{ .Values.db.name }} 
  type: ClusterIP 