apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fe.name }} 
  name: {{ .Values.fe.name }}
spec:
  ports:
  - nodePort: {{ .Values.fe.nodePort }} 
    port: {{ .Values.fe.port }} 
    protocol: TCP
    targetPort: {{ .Values.fe.port }} 
  selector:
    app: {{ .Values.fe.name }} 
  type: NodePort
